---
- hosts: all
  gather_facts: no
  connection: local



  tasks:


     - name: QUERY FORTIGATE DEVICE BY IP
       fmgr_query:
         host: "{{inventory_hostname}}"
         username: "{{ Fortimgr_user }}"
         password: "{{ Fortimgr_pass }}"
         adom: "Stations"
         device_ip: 10.52.29.7
         object: "device"

         

