---
- hosts: all
  gather_facts: no
  connection: local



  tasks:

     - debug: var=Fortimgr_user
     - debug: var=Fortimgr_pass
     - name: QUERY FORTIGATE DEVICE BY IP
       fmgr_query:
         host: "{{inventory_hostname}}"
         username: "{{ Fortimgr_user }}"
         password: "{{ Fortimgr_pass }}"
         adom: "Stations"
         device_ip: 10.52.29.7
         object: "device"

    # - name: 
    #   fortios_config:
    #     host: 10.52.29.7
    #     username: etomb
     
   #  - name: CREATE SCRIPT
   #    fmgr_script:
   #      host: "{{inventory_hostname}}"
   #      username: "{{ Fortimgr_user }}"
   #      password: "{{ Fortimgr_pass }}"
   #      adom: "root"
   #      script_name: "TestScript"
   #      script_type: "cli"
   #      script_target: "remote_device"
   #      script_description: "Create by Ansible"
   #      script_content: "get system status"

         

