---
- hosts: all
  gather_facts: no
  connection: local
  environment:
    PYTHONHTTPSVERIFY: 0
  

  tasks:


     
     
     
     - name: return next available IP address for network 192.168.10.0/24
       set_fact:
         ipaddr: "{{ lookup('nios_next_ip', '10.80.100.0/22', provider={'wapi_version': '2.1', 'host': '{{ nios_host }}', 'username': '{{ nios_username }}', 'password': '{{ nios_password}}' }) }}"

